### ISSUE TITLE
No Apollo service name found

### ISSUE THREAD

**Issue by AdrienLemaire** [ruanyl/coc-apollo#1]
Hi, and thanks for making this plugin, looking forward to it!

After installing it, I'm seeing this error in my coc log:
```
2021-02-15T09:13:11.441 ERROR (pid:24749) [extensions] - Error on active extension coc-apollo-graphql: CocApolloGraphqlExtensionError: No Apollo service name found
    at loadConfig (/home/dori/.config/coc/extensions/node_modules/coc-apollo-graphql/lib/index.js:38127:11)
    at Object.activate (/home/dori/.config/coc/extensions/node_modules/coc-apollo-graphql/lib/index.js:38861:30)
    at Object.activate (/home/dori/.vim/plugged/coc.nvim/build/index.js:228:1333)
    at t9.activate (/home/dori/.vim/plugged/coc.nvim/build/index.js:225:7211)
    at t9.setupActiveEvents (/home/dori/.vim/plugged/coc.nvim/build/index.js:225:10490)
    at t9.activateExtensions (/home/dori/.vim/plugged/coc.nvim/build/index.js:224:17268)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async MP.init (/home/dori/.vim/plugged/coc.nvim/build/index.js:254:5524)
    at async /home/dori/.vim/plugged/coc.nvim/build/index.js:129:13445 CocApolloGraphqlExtensionError: No Apollo service name found
    at loadConfig (/home/dori/.config/coc/extensions/node_modules/coc-apollo-graphql/lib/index.js:38127:11)
    at Object.activate (/home/dori/.config/coc/extensions/node_modules/coc-apollo-graphql/lib/index.js:38861:30)
    at Object.activate (/home/dori/.vim/plugged/coc.nvim/build/index.js:228:1333)
    at t9.activate (/home/dori/.vim/plugged/coc.nvim/build/index.js:225:7211)
    at t9.setupActiveEvents (/home/dori/.vim/plugged/coc.nvim/build/index.js:225:10490)
    at t9.activateExtensions (/home/dori/.vim/plugged/coc.nvim/build/index.js:224:17268)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async MP.init (/home/dori/.vim/plugged/coc.nvim/build/index.js:254:5524)
    at async /home/dori/.vim/plugged/coc.nvim/build/index.js:129:13445
2021-02-15T09:13:11.793 INFO (pid:24749) [plugin] - coc.nvim 0.0.80-fff2a86b16 initialized with node: v15.8.0 after 484ms
2021-02-15T09:13:13.501 INFO (pid:24749) [language-client-index] - eslint started with 24865
2021-02-15T09:13:13.517 INFO (pid:24749) [language-client-index] - tailwindCSS started with 24873
2021-02-15T09:13:13.528 INFO (pid:24749) [services] - registered service "tsserver"
2021-02-15T09:13:17.233 INFO (pid:24749) [attach] - receive notification: openLog []
```

Checking out the code, it seems like you're trying to extract the service name from the APOLLO_KEY string?
https://github.com/ruanyl/coc-apollo-graphql/blob/1cc73881dbf983d86ac3e9c5575f7d5c428d57e2/src/utils.ts#L1

My .env settings looks like `APOLLO_KEY=user:gh.AdrienLemaire:iatBC...5F`, which, is completely different from my service name defined in `apollo.config.js`
```js
module.exports = {
  client: {
    name: "Project [web]",
    service: {
      name: "project", // <= That's my service name
      url: process.env.GRAPHQL_URI || "http://localhost:4001/graphql",
      skipSSLValidation: true,
    },
    excludes: ["**/__tests__/**/*"],
  },
};
```

**Comment by ruanyl** [comment]
Hi @AdrienLemaire 
Now it's updated to read the service name from `apollo.config`.

But since I start this project last weekend, and it's in the very early stage, keep in mind that things may change rapidly. 
For example, I have renamed the extension to `coc-apollo`, please uninstall `coc-apollo-graphql` and install `coc-apollo`. The above issue should have been resolved.

**Comment by AdrienLemaire** [comment]
The work done so far is very impressive! Thanks a lot

**Comment by ruanyl** [comment]
And thanks for trying it out :)
Feel free to open issues if you encountered more problems with it.

**Comment by ruanyl** [comment]
@AdrienLemaire I have a question about the `apollo.config.js` above, according to the [documentation](https://www.apollographql.com/docs/devtools/apollo-config/#clientservice), if I get it correctly, the configuration you provided actually means to load schema from the endpoint `service.url`.

If you want to load schema from Apollo Engine, the config should like
```
module.exports = {
  client: {
    service: "project", // <= the service name
  },
};
```

**Comment by AdrienLemaire** [comment]
@ruanyl you're right. I updated my setup to use the apollo studio endpoint, and it seems to work.
![](https://i.imgur.com/2lkDBNu.png)

It's unclear why I only see stats on Quest and color, and why Quest has `~8s` when it obviously doesn't take that long to query a quest, but ... ^^'

**Comment by ruanyl** [comment]
@AdrienLemaire It only fetches the stats of the past 24 hours. Could that explain why some fields don't have stats?
If 8s looks unrealistic, you can verify the data from here: https://graphql.api.apollographql.com/api/graphql with query
```gql
  query FieldStats($id: ID!) {
    service(id: $id) {
      stats(from: "-86400", to: "-0") {
        fieldStats {
          groupBy {
            field
          }
          metrics {
            fieldHistogram {
              durationMs(percentile: 0.95)
            }
          }
        }
      }
    }
  }

```
With variables
```json
{
  "id": "your graph name"
}
```

With headers:
```
{
  "x-api-key": "your APOLLO_KEY"
}
```

**Comment by AdrienLemaire** [comment]
@ruanyl thanks for the data verification steps (would look great in the README too!).
I can find stats for all the fields listed in the query, but they aren't displayed

```json
{
  "data": {
    "service": {
      "stats": {
        "fieldStats": [
          {
            "groupBy": {
              "field": "Query.Quest:[Quest]"
            },
            "metrics": {
              "fieldHistogram": {
                "durationMs": 331.2588210149419
              }
            }
          },
          {
            "groupBy": {
              "field": "Quest.id:ID!"
            },
            "metrics": {
              "fieldHistogram": {
                "durationMs": 0.08863846595633577
              }
            }
          },
          {
            "groupBy": {
              "field": "Quest.name:String!"
            },
            "metrics": {
              "fieldHistogram": {
                "durationMs": 0.3794754743875782
              }
            }
          },
          {
            "groupBy": {
              "field": "Quest.skill:Skill!"
            },
            "metrics": {
              "fieldHistogram": {
                "durationMs": 1.585163230723649
              }
            }
          },
          {
            "groupBy": {
              "field": "Quest.slug:String!"
            },
            "metrics": {
              "fieldHistogram": {
                "durationMs": 0.046617034098473176
              }
            }
          },
          {
            "groupBy": {
              "field": "Quest.story:String!"
            },
            "metrics": {
              "fieldHistogram": {
                "durationMs": 0.02631410044501609
              }
            }
          },
          {
            "groupBy": {
              "field": "Quest.storybookMap:Map!"
            },
            "metrics": {
              "fieldHistogram": {
                "durationMs": 0.02063391818295823
              }
            }
          },
          {
            "groupBy": {
              "field": "Quest.updatedOn:_Neo4jDateTime!"
            },
            "metrics": {
              "fieldHistogram": {
                "durationMs": 0.015526603183834056
              }
            }
          },
          {
            "groupBy": {
              "field": "Skill.color:Color!"
            },
            "metrics": {
              "fieldHistogram": {
                "durationMs": 0.023921909495469174
              }
            }
          },
          {
            "groupBy": {
              "field": "Skill.name:SkillName!"
            },
            "metrics": {
              "fieldHistogram": {
                "durationMs": 0.038526474461548076
              }
            }
          },
          {
            "groupBy": {
              "field": "_Neo4jDateTime.day:Int"
            },
            "metrics": {
              "fieldHistogram": {
                "durationMs": 0.012275722061180229
              }
            }
          },
          {
            "groupBy": {
              "field": "_Neo4jDateTime.month:Int"
            },
            "metrics": {
              "fieldHistogram": {
                "durationMs": 0.01633898606343089
              }
            }
          },
          {
            "groupBy": {
              "field": "_Neo4jDateTime.year:Int"
            },
            "metrics": {
              "fieldHistogram": {
                "durationMs": 0.038526474461548076
              }
            }
          }
        ]
      }
    }
  }
}
```
Today, the color metric doesn't show up anymore but the skill one does. And the Quest metric looks ok with 331ms.

![](https://i.imgur.com/f5UmLxv.png)

**Comment by ruanyl** [comment]
@AdrienLemaire Because it only picks those values `> 1`, just like the apollo vscode extension :)

**Comment by AdrienLemaire** [comment]
@ruanyl awesome! Thanks for the great support!
